language: node_js

node_js: 6.5.0

before_script:
  - npm prune
  - npm install

script: npm test --coverage

deploy:
  provider: npm
  email: openhoat@gmail.com
  api_key:
    secure: Del3aSxT2GoRyjD4rHzigdsRtZV7Mja+uM/61rqvd+0XQxfynwpuY/qnTb4K4SUlG6Huo2HRB2HfSY+lbFifOibRGLE+hk5bHPI4BdI91Mfm4xQmEOE/B7KbbLDDuGXwMc05Dx6QNqlpisF6CBx87W7cVbLU7DQ+o42w5oXB8CUSKAluJi6YIi6xFpuXx/HaW7U/OJQRVd3fuMI9kvfpo/vVGicrh2wor8UPrxTkXs3A1Xl3qd5yzUDivwCTX/Be483kJnzTfnllyA9UFTqRAq46w3Is6fAZMZ959XsPIKTLt08h1nhaivLTAXThaVuW8vZCQ81sCFmmX8USSM4SWSShzSJFeoW5hKzixqr+ctsqGtf1g17l7TWXHuM2yiFKLLIrDvZg3dED9ONcuYqT2ClAsWXX1lgvsa11xHXEQnaW9n9xYqPNunIWnRZ7vpGtxiMTlehF7RgOI2EacCeOxag4uPNq2mrfn4WKXVjTPIKkLdiNP3Oaqv2f5waAESsogHEq/sGSnoFn3EG+C0kVNlad09TS1QHqTyk8C7wOwzzsssyxdcq3UoE82D4K8fjZSwX59/EHXAnPYmkwuoj/5F6N5/uq9I8jy+rew5vI/QNXuYG9ppPkQ2cQBpYcO5hNP6N/QvMdVpWFeucw2rSmm+6kKdJMIv4d2nJ+cdkJ6g0=
